version: "3.8"
services:
  react-node:
    image: node-v14
    environment:
      - PORT=3000
      - APP_DIR=/client
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:${APP_DIR}
    env_file:
      - .env
    command: "npm run dev"    




      